### ISSUE TITLE
Değişken ve metod isimleri İngilizce'ye çevrilmeli (isim -> name, yas -> age, bilgiler -> introduce).

### ISSUE THREAD

**Issue by mobilerast** [akifkomurcu/js-basic-class-interitance#1]
https://github.com/akifkomurcu/js-basic-class-interitance/blame/8193071e0c0823b28744e4f3146efdfa54af121c/index.js#L3C14-L3C14

**Comment by akifkomurcu** [comment]
değişken isimleri ingilizceye çevrildi. typescript örnekleri eklendi
